BLE
Gessler-GmbH/smp-rs pull request #5
Opened 2024-08-23 05:52 UTC by aectaan

Hi again, @SZenglein!

What's done:
* BLE transport (btw I checked update and interactive shell and it's awesome!)
* async UDP transport
* All the transports moved into the main library.
* Added CI routine for code linting, format checking and build check for 3 platforms: (linux, macOS and windows). It's possible to add routine for cross compilation for linux arm64 (raspberry and others), but it's not necessary.
* I've decided to not implement async serial - have no devices with uart, can't check. And see no reason for it, actually. Because we need to send packets with max size 128 bytes, it's simpler to make it sync, imho.

If you see something clumsy - please let me know. I'm new to Rust and might not make something as good as it could be

2024-08-26 07:47 UTC, SZenglein commented
First of all, thanks for your positive feedback on the update and shell implementation :smile:.

I'll review the PR in the coming days. 

One thing I can already say: I am not against the linting and formatting rules (quite the opposite), but it might be better to move those into another PR to keep this one focused.

2024-08-27 10:10 UTC, SZenglein commented
> Ok, I can remove it and make a dedicated PR. I combined it, because it has no influence on the source code

Right, because I usually heavily depend on rustfmt and clippy myself. I've changed my mind, just leave it in this PR. Initially I thought you applied some changes that reordered Cargo.toml which was a bit messy, but I think that was some other tool you used.

2024-08-28 07:47 UTC, aectaan commented on mcumgr-smp/Cargo.toml
> +version = "0.7.0"
Sorry for this, but it's rustfmt

2024-08-28 07:51 UTC, aectaan commented on mcumgr-smp/src/smp_framing.rs
> +pub enum SmpTransportError {
There is the deal: we can return old naming, but should add some exceptions for clippy. Otherwise action will fail on non-camel names. Until this crate is not 1.x.x it's allowed to make breaking changes. Or am I wrong? 

Decision is on you, but I would like naming in one style

2024-08-28 07:53 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
Yes. Initially I used `mcumgr-smp` 0.6.0 for interacting with my device, and realised BLE transport outside the library. That was the motivation to improve lib a bit

2024-08-28 07:57 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
> +        thread::sleep(scan_timeout);
We can make event-based handling for advertising packets, but it will be unnecessary overkill. I will rework with Tokio with possibility to select adapter.

2024-08-28 07:59 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
> +            .await?;
Yes, framing is the part of BLE stack. We can face with MTU between 23 and 512 bytes, it's result of negotiations between devices.

2024-08-28 08:00 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
> +        let res = self.notifications.next().await.unwrap();
I can filter by UUID. I had in mind that this crate will be used only with devices that has SMP service. But obviously, someone can try it with random device.

2024-08-28 08:03 UTC, aectaan commented on smp-tool/src/main.rs
> +    name: Option<String>,
Two reasons:
1. iOS & MacOS doesn't provide MAC address info for users, there are always 00:00:00:00:00:00 for all devices
2. Devices can change their BD-address. It's actual for devices with non-Public addresses and devices that have security level >1 (MITM enabled, for example)

2024-08-28 08:10 UTC, aectaan commented on mcumgr-smp/src/transport/udp/udp_sync.rs
Should I do the same for serial?

2024-08-28 08:47 UTC, SZenglein commented on mcumgr-smp/Cargo.toml
> +version = "0.7.0"
How are you running rustfmt? It does not format toml for me

2024-08-28 08:59 UTC, SZenglein commented on mcumgr-smp/src/smp_framing.rs
> +pub enum SmpTransportError {
First of all, I agree for the name change. But you only changed it in one location and I would like to change it in all locations at once (see e.g SMPFrame). So it's more of a case of not changing enough.

Small breaking changes like this are fine at this point.

Are you sure the checks are actually failing, because they do not for me?

2024-08-28 09:03 UTC, SZenglein commented on mcumgr-smp/src/transport/ble/mod.rs
> +    }
No hard opinion, I propose `from_peripheral`

2024-08-28 09:24 UTC, SZenglein commented on mcumgr-smp/src/transport/ble/mod.rs
> +        let res = self.notifications.next().await.unwrap();
But there are possibly other events that could be sent I imagine? Running something else over the same connection?

2024-08-28 09:28 UTC, SZenglein commented on mcumgr-smp/src/transport/udp/udp_sync.rs
yes

2024-08-28 09:30 UTC, SZenglein commented on smp-tool/src/main.rs
> +    name: Option<String>,
Okay then, seems legit to me.

2024-08-28 09:57 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
> +        let res = self.notifications.next().await.unwrap();
At the current state - no, because we only subscribe to SMP char. But in case when user will decide to other chars, there may be a problem.

2024-09-02 10:33 UTC, SZenglein requested changes
Remaining changes are pretty tiny. Once all conversations are addressed and resolved, I will merge.

2024-09-02 10:33 UTC, SZenglein commented on mcumgr-smp/src/transport/ble/mod.rs
> +        }
if the stream returns None (for whatever reason) you should return an error from the loop.

2024-09-02 10:33 UTC, SZenglein commented on mcumgr-smp/src/transport/ble/mod.rs
> +    pub async fn new(
I will not require you to do this, but it would be nice if you could add a short doc comment on the `new` and `from_peripheral` functions as well as on the struct itself. Just a short description what it does and how it works, nothing fancy.

2024-09-02 10:33 UTC, SZenglein commented on mcumgr-smp/src/lib.rs
>  pub mod smp_framing;
why not move this into `transport`? 

(not a blocker)

2024-09-02 10:33 UTC, SZenglein commented on smp-tool/Cargo.toml
> +version = "0.1.0"
Please also do not reorder this section

2024-09-02 10:35 UTC, SZenglein commented on mcumgr-smp/Cargo.toml
> +version = "0.7.0"
Please restore the [package] section. The rest is fine

2024-09-02 10:37 UTC, SZenglein commented on mcumgr-smp/src/transport/ble/mod.rs
> +        thread::sleep(scan_timeout);
I like your solution with the dedicated `adapters` function. Should be reasonably easy and flexible to use.

2024-09-03 20:47 UTC, aectaan commented on mcumgr-smp/src/transport/ble/mod.rs
> +        thread::sleep(scan_timeout);
Have more ideas how to make it more flexible, will bring it with new PR.

2024-09-04 14:24 UTC, SZenglein approved these changes
Okay! Let me know if you are done or if there is anything else you want to change. I will gladly merge these changes (and squash them in the process).

Can't wait to try out flashing a firmware (and more) over Bluetooth once I have the time. Thank you a lot for this awesome feature!

2024-09-04 19:20 UTC, aectaan commented
There is nothing to change right now, but I would like to collaborate on this crate in the future. Maybe will add flags for autoconfirming images after upload or something else

2024-09-05 09:31 UTC, SZenglein commented
> There is nothing to change right now, but I would like to collaborate on this crate in the future. Maybe will add flags for autoconfirming images after upload or something else. I think we are ready to merge

Sure, any (reasonable) change is very much welcome. Especially the CLI, since that has primarily been sort of a demo for the library, which it does not have to be.

2024-09-05 09:34 UTC, merged